skill_aliases = {
    "natural language processing": "Natural Language Processing",
    "nlp": "Natural Language Processing",
    "data visualization": "Data Visualization",
    "visualization": "Data Visualization",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "artificial intelligence": "Artificial Intelligence",
    "ai": "Artificial Intelligence",
    "sql": "SQL",
    "structured query language": "SQL",
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "GCP",
    "google cloud platform": "GCP",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "pbi": "Power BI",
    "python": "Python",
    "r": "R",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-learn",
    "tensorflow": "TensorFlow",
    "keras": "Keras",
    "pytorch": "PyTorch",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "spark": "Spark",
    "apache spark": "Spark",
    "hadoop": "Hadoop",
    "apache hadoop": "Hadoop",
    "git": "Git",
    "version control": "Git",
    "devops": "DevOps",
    "mlops": "MLOps",
    "ci/cd": "CI/CD",
    "continuous integration/continuous delivery": "CI/CD",
    "communication skills": "Communication",
    "strong communication": "Communication",
    "presentation skills": "Presentation Skills",
    "analytical skills": "Analytical Skills",
    "problem-solving": "Problem-Solving",
    "critical thinking": "Critical Thinking",
    "data analysis": "Data Analysis",
    "data science": "Data Science",
    "business intelligence": "Business Intelligence",
    "bi": "Business Intelligence",
    "computer vision": "Computer Vision",
    "deep learning": "Deep Learning",
    # Add more aliases as you encounter them
}